from ..job import ContainerJob, RemoteSshJob, Result


class JobEngine:
    async def spawn_container_job(self, job: ContainerJob) -> Result: ...
    async def spawn_remote_ssh_job(self, job: RemoteSshJob) -> Result: ...
