import dataclasses


@dataclasses.dataclass
class ExecResult:
    exit_code: int
    stdout: str


class JobRuntime:
    def exec(self, cmd: str, env: dict[str, str] | None = None) -> ExecResult: ...
    def is_dir(self, remote_path: str) -> bool: ...
    def list_tree(self, remote_dir: str) -> list[str]: ...
    def put_file(self, local_source: str, remote_dest: str): ...
    def get_file(self, remote_source: str, local_dest: str): ...
    def destroy(self): ...
